name: "Send approval email"
description: "Send approval email"
inputs:
  token:
    description: "GITHUB_TOKEN or repo scoped PAT"
    required: true
  email_lookup_url:
    description: "Base URL of the Apps Script web app for email lookup"
    required: true
  mail_server_username:
    description: "mail server username"
    required: true
  mail_server_password:
    description: "mail server password"
    required: true
  workshop_issue_number:
    description: "Reference of the GitHub issue associated with the workshop"
    required: true
runs:
  using: "composite"
  steps:
    - name: Look up organizer email
      id: lookup_email
      uses: ./.github/actions/lookup-email
      with:
        lookup_url: ${{ inputs.email_lookup_url }}
        github_username: ${{ github.event.issue.user.login }}

    - name: Extract workshop specific fields
      id: extract_workshop
      uses: ./.github/actions/extract-workshop-fields
      with:
        token: ${{ inputs.token }}
        repository: ${{ github.repository }}
        issue_number: ${{ inputs.workshop_issue_number }}

    - name: Send approval mail
      uses: dawidd6/action-send-mail@62a2d05b79935ad4fb90ce9079928099579c14ac # v9
      with:
        server_address: webhost.dynadot.com
        server_port: 587
        secure: false
        username: ${{ inputs.mail_server_username }}
        password: ${{ inputs.mail_server_password }}
        from: MorphoCloudPortal <no-reply@morphocloud.org>
        to: ${{ steps.lookup_email.outputs.email }}
        subject:
          "[${{ github.event.repository.name }}] Approval granted for workshop
          #${{ inputs.workshop_issue_number }}"
        convert_markdown: true
        html_body: |
          ✅ Your request for a MorphoCloud workshop has been approved.

          **What’s next?**

          - To initiate the creation of ${{ steps.extract_workshop.outputs.number_of_instances }} instances expected to be running for ${{ steps.extract_workshop.outputs.duration_days }} days, comment `/create` on the issue.

          > **Tip:** We recommend running `/create` approximately **24 hours before your workshop begins** to ensure all instances are ready in time.

          _Only one command should be used per comment._

          If you have questions, please contact [portal@morphocloud.org](mailto:portal@morphocloud.org).

          **Supported Issue Commands:**

          _The following commands can be added as comments to issue [${{ github.repository }}#${{ inputs.workshop_issue_number }}](https://github.com/${{ github.repository }}/issues/${{ inputs.workshop_issue_number }}):_

          - `/create`: Initiate the workshop instances
