name: "Check instance management approval"
description: "Check instance management approval"
inputs:
  token:
    description: "GITHUB_TOKEN or repo scoped PAT"
    required: true
  issue_number:
    description: "Issue number"
    required: true
outputs:
  is_approved:
    description: "Set to 'true' or 'false'"
    value: ${{ steps.check_approval.outputs.is_approved }}
runs:
  using: "composite"
  steps:
    - name: Check approval
      id: check_approval
      shell: bash
      run: |
        echo "Fetching labels for issue #$ISSUE_NUMBER"

        LABELS_JSON=$(gh issue view "$ISSUE_NUMBER" --json labels 2>/dev/null)
        if [ $? -ne 0 ] || [ -z "$LABELS_JSON" ]; then
          echo "Failed to fetch labels or issue does not exist."
          echo "is_approved=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "LABELS_JSON:"
        echo "$LABELS_JSON" | jq .

        # Use jq to check if the label exists
        is_approved=$(echo "$LABELS_JSON" | jq -e '[.labels[].name] | index("request:approved")' > /dev/null && echo "true" || echo "false")

        echo "is_approved [$is_approved]"
        echo "is_approved=$is_approved" >> $GITHUB_OUTPUT
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        GITHUB_TOKEN: ${{ inputs.token }}
