name: "Extract issue fields"
description: "Extract issue fields"
inputs:
  issue_number:
    description: "Issue number identifying the issue to extract fields from"
    required: true
outputs:
  email:
    description: "Email"
    value: ${{ steps.extract.outputs.email }}
runs:
  using: "composite"
  steps:
    - name: Fetch the issue
      id: read_issue_body
      shell: bash
      run: |
        body=$(gh issue view ${{ inputs.issue_number }} \
          --repo ${{ github.repo }} \
          --json body --jq '.body')
        echo "body=$body" >> $GITHUB_OUTPUT

    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.2.0
      with:
        body: ${{ steps.read_issue_body.output.body }}

    - name: Display parsed data
      shell: bash
      run: |
        echo ${{ toJSON(steps.parse.outputs.data) }} | jq .

    - name: Extract fields
      id: extract
      shell: bash
      run: |
        email=$(
          echo ${{ toJSON(steps.parse.outputs.data) }} |
          jq -r ".email.text"
        )
        echo "email=$email" >> $GITHUB_OUTPUT
