name: Course Instance Request
description:
  Issue template to request a cloud instance for a MorphoCloud course or class.
title: "Course Instance Request"
labels:
  - request-type:course-instance
  - request-creator:user
  - instance-request

body:
  - type: markdown
    attributes:
      value: |
        _The title will be automatically replaced with a standard identifier when your request is processed. Avoid including personal information in the title._
