name: Workshop Request
description: Issue template to request bulk creation of workshop instances.
title: "Workshop: "
labels:
  - request-type:workshop
  - request-creator:user

body:
  - type: markdown
    attributes:
      value: |
        _Please enter a short descriptive title for the workshop in the title bar above this text"_

  - type: dropdown
    attributes:
      label: Cloud Computing Instance Flavor
      description:
        Select the type of cloud-computing instance to create for workshop
        participants.
      options:
        - g3.large - GPU instance (16 CPUs, 60 GB RAM and 50% of A100 GPU)
        - g4.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)
        - m3.xl - General-purpose instance (32 CPUs, 125 GB RAM)
        - r3.large - Large Memory instance (64 CPUs, 500 GB RAM)
        - r3.xl - Large Memory instance (128 CPUs, 1000 GB RAM)
    validations:
      required: true

  - type: input
    attributes:
      label: Duration (days)
      description: Number of days the workshop instances should remain active.
      placeholder: "3"
    validations:
      required: true

  - type: input
    attributes:
      label: Number of Instances
      description: Total number of instances needed for the workshop.
      placeholder: "15"
    validations:
      required: true

  - type: input
    attributes:
      label: Workshop Date(s)
      description: Start date (and end date if multi-day) of the workshop.
      placeholder: "e.g., April 15, 2026 or April 15–17, 2026"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: >
        Provide details about your workshop. Approval is contingent upon a valid
        use case in the domain of 3D digital morphology.
      value: |
        **Workshop name:** 

        **Target audience:** 

        **Workshop content / goals:** 

        **Software / data to be used:** 
    validations:
      required: true


