name: Course Instance Request
description:
  Issue template to request a cloud instance for a MorphoCloud course or class.
title: "Course Instance: "
labels:
  - request-type:course-instance
  - request-creator:user
  - instance-request

body:
  - type: markdown
    attributes:
      value: |
        _Enter your full name in the title bar above (e.g., "Course Instance: Jane Doe")._

  - type: input
    id: course-team-slug
    attributes:
      label: Course Team Slug
      description: >
        The GitHub team slug for your course (provided by your instructor, e.g.,
        `morpho-course-spring-2025`).
    validations:
      required: true
