name: Workshop Request
description: Issue template to request bulk creation of workshop instances.
title: "Workshop: "
labels:
  - request-type:workshop
  - request-creator:user

body:
  - type: markdown
    attributes:
      value: |
        _Please enter a short descriptive title for the workshop in the title bar above this text"_

  - type: dropdown
    attributes:
      label: Cloud Computing Instance Flavor
      description:
        Select the type of cloud-computing instance to create for workshop
        participants.
      options:
        - g3.large - GPU instance (16 CPUs, 60 GB RAM and 50% of A100 GPU)
        - g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)
        - m3.xl - General-purpose instance (32 CPUs, 125 GB RAM)
        - r3.large - Large Memory instance (64 CPUs, 500 GB RAM)
        - r3.xl - Large Memory instance (128 CPUs, 1000 GB RAM)
    validations:
      required: true

  - type: input
    attributes:
      label: Duration (days)
      description: Number of days the workshop instances should remain active.
      placeholder: "3"
    validations:
      required: true

  - type: input
    attributes:
      label: Number of Instances
      description: Total number of instances needed for the workshop.
      placeholder: "15"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description:
        Describe the workshop content, target audience, and your usage needs for
        the instances. Approval of the request is contingent upon a valid use
        case in the domain of 3D digital morphology.
    validations:
      required: true

  - type: input
    attributes:
      label: ORCID
      description: Enter your ORCID iD for identification purposes.
      placeholder: 0000-0000-0000-0000
    validations:
      required: true

  - type: input
    attributes:
      label: Email
      description: Primary email address of the workshop organizer.
    validations:
      required: true

  - type: input
    attributes:
      label: Confirm Email
      description:
        Re-enter the organizer email address to confirm it is correct.
    validations:
      required: true
