name: "Send email"
description: "Send email with instance connection details"
inputs:
  to:
    description: "Recipient of the instance connection details"
    required: true
  mail_server_username:
    description: "mail server username"
    required: true
  mail_server_password:
    description: "mail server password"
    required: true
  instance_name:
    description: "Name of the instance to connect to"
    required: true
  connection_url:
    description: "Guacamole Connection URL"
    required: true
  instance_ip:
    description: "Public IP associated with the instance"
    required: true
  instance_pwd:
    description: "Passphrase associated with the instance"
    required: true
runs:
  using: "composite"
  steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@2cea9617b09d79a095af21254fbcb7ae95903dde # v3.12.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ inputs.mail_server_username }}
        password: ${{ inputs.mail_server_password }}
        from: MorphoCloudPortal
        to: ${{ inputs.to }}
        subject:
          "[${{ github.event.repository.name }}] Instance ${{
          inputs.instance_name }} created"
        convert_markdown: true
        html_body: |
          Your MorphoCloud instance is up and running:

          * **Graphical User Interface (GUI)**: Use the weblink provided below to access your instance.
          * **Command Line Access**: Use the SSH information provided below to access your instance
          from the command line.

          In both cases, username is **exouser** and the passphrase is provided.

          **Important Notes:**

          - Each session is limited to 4h, after which your instance is automatically shelved.
          - To unshelve an existing instance, use the`/unshelve` command.
          - To shelve an instance and preserve your allocation, use the `/shelve` command.
          - To obtain the latest set of access credentials, use the `/email` command.

          If you have questions, please contact [morphocloud-support@gmail.com](mailto:morphocloud-support@gmail.com).

          **Connection Methods:**

          - Web connect: ${{ inputs.connection_url }}
          - SSH: `ssh exouser@${{ inputs.instance_ip }}`

          **Credentials:**

          - Username: **exouser**
          - Passphrase: `${{ inputs.instance_pwd }}`
