name: "Define instance name"
description: "Define instance name"
inputs:
  issue_number:
    description: "Issue number 'NNN' used to set the instance name"
    required: true
  prefix:
    description:
      "Optional string to prepend. If prefix is not empty, output is of the form
      '<PREFIX>_instance-NNN'."
outputs:
  instance_name:
    description:
      "Name of the instance formatted as '[<PREFIX>_]instance-NNN' where 'NNN'
      is the issue number"
    value: ${{ steps.define.outputs.instance_name }}
  instance_prefix:
    description:
      "If input prefix is not empty, instance prefix is set to '<PREFIX>_'"
    value: ${{ steps.define.outputs.instance_prefix }}
runs:
  using: "composite"
  steps:
    - name: "Define instance name"
      id: define
      shell: bash
      run: |
        instance_prefix=${PREFIX:+${PREFIX}_}
        instance_name="${instance_prefix}instance-$ISSUE_NUMBER"
        echo "instance_prefix=$instance_prefix" >> $GITHUB_OUTPUT
        echo "instance_name=$instance_name" >> $GITHUB_OUTPUT
      env:
        PREFIX: ${{ inputs.prefix }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
