name: "Check volume exists"
description: "Check volume exists"
inputs:
  os_cloud:
    description:
      "Name of the OpenStack cloud allocation to select openstack auth settings
      defined in '.config/openstack/clouds.yaml'"
    required: false
  os_application_credential_id:
    description: "OpenStack application credential ID (alternative to os_cloud)"
  os_application_credential_secret:
    description:
      "OpenStack application credential secret (alternative to os_cloud)"
  os_auth_url:
    description:
      "OpenStack identity endpoint URL (required when using app credentials)"
  os_identity_api_version:
    description: "OpenStack identity API version"
    default: "3"
  os_auth_type:
    description: "OpenStack auth type"
    default: "v3applicationcredential"
  volume_name:
    description: "Name of the volume"
    required: true
outputs:
  exists:
    description: "Set to 'true' or 'false'"
    value: ${{ steps.check_volume.outputs.exists }}
runs:
  using: "composite"
  steps:
    - name: Check volume exists
      id: check_volume
      shell: bash
      run: |
        source ~/venv/bin/activate

        volume=$(openstack volume list -f json | \
          jq \
            --arg volume_name "$VOLUME_NAME" \
            -c '.[] | select(.Name != null) | select(.Name == $volume_name)' | \
          jq -r '.Name' | tail -1)

        [[ $volume == "$VOLUME_NAME" ]] && exists="true" || exists="false"

        echo "exists [$exists]"
        echo "exists=$exists" >> $GITHUB_OUTPUT
      env:
        OS_CLOUD: ${{ inputs.os_cloud }}
        OS_APPLICATION_CREDENTIAL_ID: ${{ inputs.os_application_credential_id }}
        OS_APPLICATION_CREDENTIAL_SECRET:
          ${{ inputs.os_application_credential_secret }}
        OS_AUTH_URL: ${{ inputs.os_auth_url }}
        OS_IDENTITY_API_VERSION: ${{ inputs.os_identity_api_version }}
        OS_AUTH_TYPE: ${{ inputs.os_auth_type }}
        VOLUME_NAME: ${{ inputs.volume_name }}
