name: Approve Instance Management from Workflow

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: number
      command_name:
        description: "Name of the command to execute: approve, unapprove"
        required: true
        type: string
  workflow_call:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: number
      command_name:
        description: "Name of the command to execute: approve, unapprove"
        required: true
        type: string
permissions:
  issues: write
  checks: read

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Approve Instance Management (comment)
        run: |
          gh issue comment $ISSUE_NUMBER \
            -b "Command <tt>$COMMAND_NAME</tt> issued by **approve-instance-from-workflow.yml** workflow. \
            See details [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
          COMMAND_NAME: ${{ inputs.command_name }}

      - name: Approve Instance Management (action)
        uses: ./.github/actions/update-approval
        with:
          issue_number: ${{ inputs.issue_number }}
          command_name: ${{ inputs.command_name }}
          instance_name_prefix: ${{ vars.INSTANCE_NAME_PREFIX }}
          token: ${{ secrets.GITHUB_TOKEN }}
          string_encryption_key: ${{ secrets.STRING_ENCRYPTION_KEY }}
          mail_server_username: ${{secrets.MAIL_USERNAME}}
          mail_server_password: ${{secrets.MAIL_PASSWORD}}
