name: Control Instance

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start:
    runs-on: self-hosted
    if:
      ${{ !github.event.issue.pull_request &&
      contains(github.event.comment.body, '/start') }}
    steps:
      - run: |
          echo Starting instance associated with issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

      - name: Extract email
        id: extract
        run: |
          email=$(
            echo ${{ toJSON(steps.parse.outputs.data) }} |
            jq -r ".email.text"
          )
          echo "email=$email" >> $GITHUB_OUTPUT

      - name: Send mail
        uses: dawidd6/action-send-mail@2cea9617b09d79a095af21254fbcb7ae95903dde # v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: MorphoCloudPortal
          to: ${{ steps.extract.outputs.email }}
          subject:
            "[MorphoCloudPortal] Instance ${{ github.event.issue.number }}
            started"
          body: Instance ${{ github.event.issue.number }} started

  stop:
    runs-on: self-hosted
    if:
      ${{ !github.event.issue.pull_request &&
      contains(github.event.comment.body, '/stop') }}
    steps:
      - run: |
          echo Stopping instance associated with issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0

      - name: Extract email
        id: extract
        run: |
          email=$(
            echo ${{ toJSON(steps.parse.outputs.data) }} |
            jq -r ".email.text"
          )
          echo "email=$email" >> $GITHUB_OUTPUT

      - name: Send mail
        uses: dawidd6/action-send-mail@2cea9617b09d79a095af21254fbcb7ae95903dde # v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: MorphoCloudPortal
          to: ${{ steps.extract.outputs.email }}
          subject:
            "[MorphoCloudPortal] Instance ${{ github.event.issue.number }}
            stopped"
          body: Instance ${{ github.event.issue.number }} stopped
