name: Create Instance

on:
  issue_comment:
    types: [created]

jobs:
  create:
    runs-on: self-hosted
    if:
      ${{ !github.event.issue.pull_request &&
      contains(github.event.issue.labels.*.name, 'request-type:instance') && (
      contains(github.event.comment.body, '/create') ) }}
    steps:
      - name: create command
        id: create_command
        uses: github/command@v2.0.3
        with:
          command: "/create"
          reaction: "rocket"
          allowed_contexts: "issue"
          permissions: "read,triage,write,maintain,admin"
          allowlist:
            "${{ vars.MORPHOCLOUD_GITHUB_ADMINS }},${{
            github.event.issue.user.login }},${{
            join(github.event.issue.assignees.*.login, ',') }}"

      - uses: actions/checkout@v6

      - uses: actions/create-github-app-token@v2.2.0
        id: app-token
        with:
          app-id: ${{ vars.MORPHOCLOUD_WORKFLOW_APP_ID }}
          private-key: ${{ secrets.MORPHOCLOUD_WORKFLOW_APP_PRIVATE_KEY }}

      - name: Create instance
        uses: ./.github/actions/create-instance
        with:
          os_cloud: ${{ vars.MORPHOCLOUD_OS_CLOUD }}
          issue_number: ${{ github.event.issue.number }}
          instance_name_prefix: ${{ vars.INSTANCE_NAME_PREFIX }}
          volume_name_suffix: ${{ vars.VOLUME_NAME_SUFFIX }}
          token: ${{ secrets.GITHUB_TOKEN }}
          app_token: ${{ steps.app-token.outputs.token }}
          org: ${{ github.repository_owner }}
          users_team_slug: ${{ vars.MORPHOCLOUD_USERS_TEAM_SLUG }}
          issue_creator: ${{ github.event.issue.user.login }}
          email_lookup_url: ${{ vars.MORPHOCLOUD_EMAIL_LOOKUP_URL }}
          string_encryption_key: ${{ secrets.STRING_ENCRYPTION_KEY }}
          mail_server_username: ${{secrets.MAIL_USERNAME}}
          mail_server_password: ${{secrets.MAIL_PASSWORD}}
