name: "Notify Admins of Workshop Request"
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
  workflow_call:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: string

jobs:
  request_notify_admins:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Inputs
        id: collect_inputs
        shell: bash
        run: |
          echo "EVENT_NAME [$EVENT_NAME]"
          if [[ "$EVENT_NAME" == "issues" ]]; then
            issue_number=${{ github.event.issue.number || inputs.issue_number }}
          elif [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then
            issue_number=${{ github.event.inputs.issue_number }}
          else
            echo "::error ::Unsupported EVENT_NAME [$EVENT_NAME]"
            exit 1
          fi
          if [[ -z "$issue_number" || "$issue_number" == "null" ]]; then
            echo "::error ::issue_number not provided"
            exit 1
          fi
          echo "issue_number=$issue_number" >> $GITHUB_OUTPUT
        env:
          EVENT_NAME: ${{ github.event_name }}

      - name: Send mail (workshop approval requested)
        uses: dawidd6/action-send-mail@6d98ae34d733f9a723a9e04e94f2f24ba05e1402 # v6
        with:
          server_address: webhost.dynadot.com
          server_port: 587
          secure: false
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: MorphoCloudPortal <no-reply@morphocloud.org>
          to: ${{ vars.MORPHOCLOUD_GITHUB_ADMIN_EMAILS }}
          subject:
            "[${{ github.event.repository.name }}] Workshop approval requested
            by @${{ github.event.issue.user.login }}"
          body: |
            @${{ github.event.issue.user.login }} has submitted a new workshop request.

            Review and approve or reject it at:
            https://github.com/${{ github.repository }}/issues/${{ steps.collect_inputs.outputs.issue_number }}
