name: Update Issue from Workflow

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: number
      command_name:
        description:
          "Name of the command to execute: encode_email, decode_email"
        required: true
        type: string
  workflow_call:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
        type: string
      command_name:
        description:
          "Name of the command to execute: encode_email, decode_email"
        required: true
        type: string
permissions:
  issues: write
  checks: read

jobs:
  control:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: Update issue
        uses: ./.github/actions/update-issue-description
        with:
          issue_number: ${{ inputs.issue_number }}
          command_name: ${{ inputs.command_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          string_encryption_key: ${{ secrets.STRING_ENCRYPTION_KEY }}
